import tsParser from '@typescript-eslint/parser';

export default [
  {
    ignores: [
      'public/ocr/**',
      'public/service-worker.js',
      'src_old/**',
      'dist/**',
      'node_modules/**',
      'vite.config.ts',
      'vite.config.js',
    ],
  },
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        ImageData: 'readonly',
        ImageBitmap: 'readonly',
        createImageBitmap: 'readonly',
        ImageBitmapOptions: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Storage: 'readonly',
        crypto: 'readonly',
        SubtleCrypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        performance: 'readonly',
        // Media APIs
        MediaStream: 'readonly',
        // Geolocation API
        GeolocationPosition: 'readonly',
        GeolocationPositionError: 'readonly',
        PermissionState: 'readonly',
        PermissionName: 'readonly',
        // IndexedDB
        IDBDatabase: 'readonly',
        IDBOpenDBRequest: 'readonly',
        IDBRequest: 'readonly',
        indexedDB: 'readonly',
        // Service Worker and Web Worker globals
        self: 'readonly',
        caches: 'readonly',
        postMessage: 'readonly',
        WebAssembly: 'readonly',
        MessageChannel: 'readonly',
        // Node.js process (for some build tools)
        process: 'readonly',
        regeneratorRuntime: 'readonly',
      },
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-undef': 'error',
      'no-useless-escape': 'error',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // Disable no-undef for TypeScript files since TypeScript handles this
      'no-undef': 'off',
    },
  },
  {
    files: ['**/*.test.{js,jsx,ts,tsx}', '**/*.spec.{js,jsx,ts,tsx}'],
    languageOptions: {
      globals: {
        global: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        test: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
      },
    },
  },
];