import type { Store } from './types';

export const storesMock: Store[] = [
  {
    id: 'gp-leclerc-bas-du-fort',
    name: 'E.Leclerc Bas du Fort',
    brand: 'E.Leclerc',
    territory: 'gp',
    address: 'Bas du Fort',
    city: 'Le Gosier',
    postalCode: '97190',
    lat: 16.2148,
    lon: -61.5111,
    services: { inStore: true, drive: true, delivery: false },
  },
  {
    id: 'gp-u-baie-mahault',
    name: 'U Baie-Mahault',
    brand: 'Système U',
    territory: 'gp',
    address: 'Zone de Jarry',
    city: 'Baie-Mahault',
    postalCode: '97122',
    lat: 16.2425,
    lon: -61.5881,
    services: { inStore: true, drive: true, delivery: true },
  },
  {
    id: 'gp-super-u-sainte-anne',
    name: 'Super U Sainte-Anne',
    brand: 'Système U',
    territory: 'gp',
    city: 'Sainte-Anne',
    postalCode: '97180',
    lat: 16.2256,
    lon: -61.3862,
    services: { inStore: true, drive: false, delivery: false },
  },
  {
    id: 'gp-carrefour-destinrelles',
    name: 'Carrefour Destrellan',
    brand: 'Carrefour',
    territory: 'gp',
    city: 'Baie-Mahault',
    postalCode: '97122',
    lat: 16.2668,
    lon: -61.5849,
    services: { inStore: true, drive: true, delivery: true },
  },
];

/**
 * Fetch stores for a territory.
 * Tries the bundled osm-stores JSON first (generated by the auto-scraper pipeline),
 * then falls back to the static mock list so the UI always has data to show.
 */
export async function fetchStores(territory?: string): Promise<Store[]> {
  try {
    const response = await fetch('/data/osm-stores.json');
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const raw: unknown = await response.json();
    const all: Store[] = Array.isArray(raw) ? (raw as Store[]) : [];
    return territory ? all.filter((s) => s.territory === territory) : all;
  } catch {
    // Network unavailable or file not yet generated — return static seed data
    return territory ? storesMock.filter((s) => s.territory === territory) : storesMock;
  }
}
