name: 🖼️ Assets Check + Optimization

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 📦 Install tools
        run: |
          npm install sharp --save

      - name: 🧪 Run assets analyzer
        run: node scripts/check-assets.mjs
