#!/bin/bash
# WebP Conversion Script
# Install webp tools first: sudo apt-get install webp

echo "Converting images to WebP format..."

cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/auchan.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/auchan.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/carrefour.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/carrefour.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/casino.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/casino.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/coccinelle.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/coccinelle.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/contact.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/contact.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/ecomax.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/ecomax.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/hyperu.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/hyperu.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/intermarché.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/intermarché.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/jumbo.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/jumbo.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leaderprice.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leaderprice.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leclerc.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leclerc.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/market.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/market.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/monoprix.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/monoprix.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/placeholder.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/placeholder.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/promocash.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/promocash.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/proxi.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/proxi.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/score.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/score.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/spar.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/spar.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/superu.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/superu.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/tiprix.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/tiprix.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/u_express.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/u_express.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/utile.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/utile.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/carrefour.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/carrefour.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/intermarche.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/intermarche.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/leader-price.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/leader-price.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/no-image.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/no-image.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/score.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/score.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/store.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/store.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/super-u.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/super-u.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/milk.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/milk.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/oil.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/oil.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/pasta.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/pasta.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/rice.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/rice.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/sugar.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/sugar.webp"
cwebp -q 85 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/og-cover.jpg" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/og-cover.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/public/icon.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/public/icon.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/splash_lancement_appli.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/splash_lancement_appli.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/A_2D_digital_graphic_design_image_features_a_dark_.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/A_2D_digital_graphic_design_image_features_a_dark_.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/A_QR_code_in_a_square_digital_image_is_displayed_i.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/A_QR_code_in_a_square_digital_image_is_displayed_i.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/A_digital_screenshot_and_a_mockup_of_the_web_appli.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/A_digital_screenshot_and_a_mockup_of_the_web_appli.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/A_favicon_in_digital_graphic_design_features_a_shi.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/A_favicon_in_digital_graphic_design_features_a_shi.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/A_pair_of_digital_screenshots_displays_the_launch_.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/A_pair_of_digital_screenshots_displays_the_launch_.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/A_webpage_screenshot_screenshot_titled__A_KI_PRI_S.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/A_webpage_screenshot_screenshot_titled__A_KI_PRI_S.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Affiches colorées de l'application A ki pri sa yé.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Affiches colorées de l'application A ki pri sa yé.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Application _A KI PRI SA YÉ_.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Application _A KI PRI SA YÉ_.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/affiches_colorees.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/affiches_colorees.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/app_banner.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/app_banner.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/budget.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/budget.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/carte_dom.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/carte_dom.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/icons/icon-192.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/icons/icon-192.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/icons/icon-512.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/icons/icon-512.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/lancement.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/lancement.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/maitrise_budget.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/maitrise_budget.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/palmares.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/palmares.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/pub_culturelle.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/pub_culturelle.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/splash.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/splash.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/vie_chere.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Assets/vie_chere.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Carte des Territoires d'Outre-Mer.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Carte des Territoires d'Outre-Mer.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/ChatGPT Image 30 juin 2025, 20_40_42.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/ChatGPT Image 30 juin 2025, 20_40_42.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Gérez Votre Budget Facilement.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Gérez Votre Budget Facilement.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Lancement de l'appli A KI PRI SA YÉ.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Lancement de l'appli A KI PRI SA YÉ.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Le visuel officiel PWA.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Le visuel officiel PWA.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Lutte contre la vie chère.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Lutte contre la vie chère.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Maîtrisez votre budget avec Ki Pri.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Maîtrisez votre budget avec Ki Pri.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Palmarès_ Classement des Meilleures Enseignes.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Palmarès_ Classement des Meilleures Enseignes.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Promotion de l'application _A KI PRI SA YÉ_.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Promotion de l'application _A KI PRI SA YÉ_.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/Publicité Moderne et Culturelle.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/Publicité Moderne et Culturelle.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-darkness-pro/public/icons/icon-192.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-darkness-pro/public/icons/icon-192.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-darkness-pro/public/icons/icon-512.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-darkness-pro/public/icons/icon-512.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-functional/public/icons/icon-192.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-functional/public/icons/icon-192.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-functional/public/icons/icon-512.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/a-ki-pri-sa-ye-functional/public/icons/icon-512.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/aki-prisaye-pwa/src/assets/logo.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/aki-prisaye-pwa/src/assets/logo.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/aki-prisaye-pwa/src/assets/outremer_carte.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/aki-prisaye-pwa/src/assets/outremer_carte.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/banniere_site.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/banniere_site.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/auchan.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/auchan.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/carrefour.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/carrefour.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/casino.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/casino.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/coccinelle.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/coccinelle.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/contact.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/contact.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/ecomax.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/ecomax.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/hyperu.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/hyperu.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/intermarché.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/intermarché.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/jumbo.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/jumbo.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/leaderprice.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/leaderprice.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/leclerc.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/leclerc.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/market.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/market.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/monoprix.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/monoprix.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/placeholder.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/placeholder.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/promocash.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/promocash.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/proxi.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/proxi.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/score.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/score.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/spar.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/spar.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/superu.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/superu.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/tiprix.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/tiprix.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/u_express.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/u_express.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/utile.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/assets/brands/utile.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/carrefour.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/carrefour.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/intermarche.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/intermarche.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/leader-price.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/leader-price.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/no-image.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/no-image.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/score.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/score.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/store.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/store.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/super-u.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/icons/super-u.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/milk.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/milk.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/oil.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/oil.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/pasta.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/pasta.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/rice.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/rice.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/sugar.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/img/sugar.webp"
cwebp -q 85 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/og-cover.jpg" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/og-cover.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/public/icon.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/public/icon.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/splash_lancement_appli.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/dist/client/splash_lancement_appli.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/favicon.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/favicon.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/favicon.png.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/favicon.webp.png"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/icon_512.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/icon_512.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/logo_hd_4k.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/logo_hd_4k.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/auchan.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/auchan.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/carrefour.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/carrefour.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/casino.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/casino.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/coccinelle.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/coccinelle.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/contact.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/contact.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/ecomax.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/ecomax.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/hyperu.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/hyperu.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/intermarché.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/intermarché.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/jumbo.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/jumbo.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leaderprice.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leaderprice.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leclerc.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/leclerc.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/market.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/market.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/monoprix.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/monoprix.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/placeholder.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/placeholder.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/promocash.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/promocash.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/proxi.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/proxi.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/score.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/score.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/spar.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/spar.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/superu.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/superu.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/tiprix.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/tiprix.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/u_express.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/u_express.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/utile.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/assets/brands/utile.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/carrefour.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/carrefour.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/intermarche.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/intermarche.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/leader-price.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/leader-price.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/no-image.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/no-image.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/score.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/score.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/store.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/store.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/super-u.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/icons/super-u.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/milk.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/milk.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/oil.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/oil.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/pasta.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/pasta.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/rice.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/rice.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/sugar.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/img/sugar.webp"
cwebp -q 85 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/og-cover.jpg" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/og-cover.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/public/icon.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/public/icon.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/public/splash_lancement_appli.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/public/splash_lancement_appli.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/pwa_icon_192.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/pwa_icon_192.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/pwa_icon_256.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/pwa_icon_256.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/pwa_icon_512.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/pwa_icon_512.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/qr_akiprisaye.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/qr_akiprisaye.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/src/assets/logo.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/src/assets/logo.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/src/assets/outremer_carte.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/src/assets/outremer_carte.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/version_fond_sombre.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/version_fond_sombre.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/web/src/assets/logo.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/web/src/assets/logo.webp"
cwebp -q 80 "/home/runner/work/akiprisaye-web/akiprisaye-web/web/src/assets/outremer_carte.png" -o "/home/runner/work/akiprisaye-web/akiprisaye-web/web/src/assets/outremer_carte.webp"

echo "WebP conversion completed!"