/**
 * Jeu de données multi-territoires réaliste pour le Panier Anti-Crise
 * Version: 1.0.0
 * 
 * Couvre: 971 (Guadeloupe), 972 (Martinique), 973 (Guyane), 974 (La Réunion)
 * 
 * Objectifs:
 * - Tester comparaisons inter-territoires
 * - Valider stabilité des prix par territoire
 * - Vérifier exclusions promo et instabilité
 * - Confirmer panier anti-crise par territoire
 * 
 * Données cohérentes avec la réalité DOM:
 * - Écarts logistiques réels (Guyane plus cher)
 * - Aucun biais promotionnel
 * - Cas limites inclus volontairement
 */

import { PriceObservation } from '../antiCrisisBasketService.js';

export const priceObservationsMultiTerritories: PriceObservation[] = [
  // =====================================================
  // 🟦 PRODUIT DE RÉFÉRENCE — RIZ 1KG (ANTI-CRISE)
  // Stable, présent dans tous les territoires
  // Doit être inclus dans le panier anti-crise de chaque territoire
  // =====================================================

  // ───── 971 — Guadeloupe
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.29,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.45,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.30,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.46,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.29,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.47,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.30,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.46,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.29,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.48,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },

  // ───── 972 — Martinique
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 1.35,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 1.50,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 1.36,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 1.51,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 1.35,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 1.52,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 1.36,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 1.51,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 1.35,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 1.50,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },

  // ───── 973 — Guyane (plus cher, logistique)
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cg_973',
    storeName: 'Carrefour Guyane',
    price: 1.55,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_973',
    storeName: 'Leader Price',
    price: 1.70,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cg_973',
    storeName: 'Carrefour Guyane',
    price: 1.58,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_973',
    storeName: 'Leader Price',
    price: 1.72,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cg_973',
    storeName: 'Carrefour Guyane',
    price: 1.56,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_973',
    storeName: 'Leader Price',
    price: 1.71,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cg_973',
    storeName: 'Carrefour Guyane',
    price: 1.57,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_973',
    storeName: 'Leader Price',
    price: 1.70,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cg_973',
    storeName: 'Carrefour Guyane',
    price: 1.56,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_973',
    storeName: 'Leader Price',
    price: 1.71,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },

  // ───── 974 — La Réunion
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_974',
    storeName: 'Leader Price',
    price: 1.32,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_974',
    storeName: 'Carrefour Market',
    price: 1.48,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_974',
    storeName: 'Leader Price',
    price: 1.34,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_974',
    storeName: 'Carrefour Market',
    price: 1.49,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_974',
    storeName: 'Leader Price',
    price: 1.33,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_974',
    storeName: 'Carrefour Market',
    price: 1.50,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_974',
    storeName: 'Leader Price',
    price: 1.32,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_974',
    storeName: 'Carrefour Market',
    price: 1.49,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'lp_974',
    storeName: 'Leader Price',
    price: 1.33,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
  {
    productId: 'p_rice_1kg',
    productName: 'Riz long grain 1kg',
    category: 'Épicerie',
    storeId: 'cm_974',
    storeName: 'Carrefour Market',
    price: 1.48,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },

  // =====================================================
  // ❌ PRODUIT PROMO — SODA 1.5L (À EXCLURE)
  // Promo ponctuelle en Guadeloupe, variance trop élevée
  // =====================================================
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.85,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.90,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 0.95, // ⚠️ Promo ponctuelle unique
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.88,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.85,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.90,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.86,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.89,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'lp_971',
    storeName: 'Leader Price',
    price: 1.85,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
  {
    productId: 'p_soda_15l',
    productName: 'Soda cola 1.5L',
    category: 'Boissons',
    storeId: 'cm_971',
    storeName: 'Carrefour Market',
    price: 1.90,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },

  // =====================================================
  // ❌ PRODUIT INSTABLE — HUILE 1L (À EXCLURE)
  // Variance trop élevée en Martinique
  // =====================================================
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 2.1,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 2.5,
    date: new Date('2025-12-08'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 2.95, // Forte hausse
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 2.55,
    date: new Date('2025-12-15'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 2.4,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 2.52,
    date: new Date('2025-12-22'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 2.15,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 2.48,
    date: new Date('2025-12-29'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'u_972',
    storeName: 'Super U',
    price: 2.85,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
  {
    productId: 'p_oil_1l',
    productName: 'Huile végétale 1L',
    category: 'Épicerie',
    storeId: 'cm_972',
    storeName: 'Carrefour Market',
    price: 2.50,
    date: new Date('2026-01-05'),
    source: 'observation_directe',
  },
];

/**
 * ✅ RÉSULTATS ATTENDUS PAR TERRITOIRE
 * 
 * Territoire | Produit retenu    | Enseigne         | Prix moyen
 * -----------|-------------------|------------------|------------
 * 971        | Riz 1kg          | Leader Price     | ~1.29€
 * 972        | Riz 1kg          | Super U          | ~1.35€
 * 973        | Riz 1kg          | Carrefour Guyane | ~1.56€
 * 974        | Riz 1kg          | Leader Price     | ~1.33€
 * 
 * Produits exclus:
 * - Soda 1.5L (971): Promo ponctuelle, variance élevée
 * - Huile 1L (972): Prix instable, coefficient de variation > 15%
 * 
 * Principe fondamental:
 * ❌ JAMAIS de comparaison inter-territoires
 * ✅ Analyse indépendante par territoire
 * ✅ Écarts logistiques réels DOM respectés (Guyane plus cher)
 */
