#!/usr/bin/env node
/**
 * generate-index.mjs
 * Scans src/pages for .tsx files and generates src/pages/index.ts exporting them
 */
import fs from 'fs/promises'
import path from 'path'
const pagesDir = path.resolve(process.cwd(), 'src', 'pages')
const outFile = path.join(pagesDir, 'index.ts')

async function scanPages() {
  const entries = await fs.readdir(pagesDir, { withFileTypes: true })
  const files = entries
    .filter((e) => e.isFile() && e.name.endsWith('.tsx') && e.name !== 'index.ts')
    .map((e) => e.name)

  const exports = files
    .map((f) => {
      const name = path.basename(f, '.tsx')
      return `export { default as ${name} } from './${name}'`
    })
    .join('\n')

  const header = `// AUTO-GENERATED by scripts/generate-index.mjs — do not edit\n` + `// Generated at: ${new Date().toISOString()}\n\n`
  await fs.writeFile(outFile, header + exports + '\n')
  console.info('Wrote', outFile)
}

scanPages().catch((err) => {
  console.error(err)
  process.exit(1)
})
