name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test --if-present

      - name: Build project
        run: npm run build

      - name: Run end-to-end tests
        run: |
          npx http-server ./dist -p 3000 &   # lance serveur local
          sleep 10
          curl -I http://localhost:3000/ | grep "200 OK"
          curl -I http://localhost:3000/compare | grep "200 OK"
          curl -I http://localhost:3000/actualites | grep "200 OK"